name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_RIVER_03C136303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
      
      # Set environment variables in Azure Static Web App
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Add step to debug environment variables
      - name: Debug Environment Variables
        run: |
          echo "OPENAI_API_KEY exists: ${{ secrets.OPENAI_API_KEY != '' }}"
          echo "ANTHROPIC_API_KEY exists: ${{ secrets.ANTHROPIC_API_KEY != '' }}"
          echo "MISTRAL_API_KEY exists: ${{ secrets.MISTRAL_API_KEY != '' }}"
          echo "GOOGLE_API_KEY exists: ${{ secrets.GOOGLE_API_KEY != '' }}"
          echo "Azure Static Web App name: my-first-static-web-app"
      
      - name: Set App Settings in Azure Static Web App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az staticwebapp appsettings set --name my-first-static-web-app --resource-group rg-training --setting-names \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}" \
            MISTRAL_API_KEY="${{ secrets.MISTRAL_API_KEY }}" \
            GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_RIVER_03C136303 }}
          action: "close"
          app_location: "/" # Required parameter

